# Generated by Django 2.2.16 on 2022-03-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220301_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aurhor',
            new_name='author',
        ),
    ]
